### ISSUE TITLE
Milestones to v1

### ISSUE THREAD

**Issue by greleigh** [greleigh/Logic-GU-new#1]
### Content
  - [ ] Update content **everywhere**

### Front page
  - [ ] Add sample news items
  - [ ] Add location to seminars
  - [ ] Which categories should be featured?

### Profiles
  - [X] Make list compact
  - [ ] Compress entries further?
  - [ ] List of publications?

### Seminars
  - [X] Remove ‘featured’ and unneeded headings
  - [ ] Seminar index pages are broken everywhere (currently hardcoded)
  - [ ] Fix dates on all lists

### Activities
  - [ ] Migrate from existing (<https://logic-gu.se/activities>) 
  - [ ] Use collection for these (as an ‘event’?)

### MiL
- [X] Fix link and embedded poster.

### Navbar
- [ ] Other contains only resources?
- [ ] Add home button to the nav list (when you are not in the home already if possible)

### Remove unused
- [ ] ‘blog' posts
- [ ] scripts, etc (Jupyter, etc)
